#! /bin/bash

cd $1
for file in *; do
  if [[ -d "${file}" ]]; then
    tar --exclude='node_modules' \
        --exclude='bower_components' \
        --exclude='.sass-cache' /
        -zcvf "${file}".tar.gz "${file}"
  fi
done

